version: "3.6"
services: 
    python:
        build: .
        volumes:
            - .:/home/src
            - /dev/input:/dev/input
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
            - "/dev/input/event5:/dev/input/event5"
